#!/bin/bash
#BSUB -J deepreach_template            # Job name
#BSUB -q lee_gpu                       # GPU queue
#BSUB -gpu "num=1:gmodel=NVIDIAH100PCIe:mode=shared:mps=yes"
#BSUB -n 1                         # 1 CPU core is enough for this
#BSUB -W 48:00                     # Wall time limit (hh:mm)
#BSUB -R "rusage[mem=8GB]"         # Reserve 8 GB RAM
#BSUB -o deepreach.%J.out          # STDOUT log
#BSUB -e deepreach.%J.err          # STDERR log

# Load your environment
source ~/.bashrc
conda activate /rsstu/users/d/dlee48/HRI-NCSU_LearningEnhancedMotionPlanning/xinlei/conda/conda_env/deepreach

# Go to your DeepReach repo
cd /rsstu/users/d/dlee48/HRI-NCSU_LearningEnhancedMotionPlanning/xinlei/projects/DeepReach_Deployment

# Run the experiment
python run_experiment.py \
  --mode train \
  --experiment_class DeepReach \
  --dynamics_class TwoDubins3DLeaderFollower \
  --experiment_name twoDubins3DLeaderFollower_trial_1_Jan_10 \
  --minWith target \
  --angle_alpha_factor 1.2 \
  --set_mode avoid \
  --num_epochs 300000 \
  --numpoints 200000 \
  --gamma 0.7 \
  --tMax 15 \
  --deepreach_model vanilla \
  --value_normto 1.0 \
  --pretrain \
  --pretrain_iters 5000
  # --use_wandb

echo "DeepReach job finished."